name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.AZURE_REGISTRY_URL }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.AZURE_REGISTRY_URL }}.azurecr.io/mlops-gitact-run:latest
            ${{ secrets.AZURE_REGISTRY_URL }}.azurecr.io/mlops-gitact-run:${{ github.sha }}
            ${{ secrets.AZURE_REGISTRY_URL }}.azurecr.io/mlops-gitact-run:${{ github.run_number }}
