name: Python MLOps Pipeline

on:
  push:
    branches:
    - main
    # paths:
  # - '.github/workflows/python-checks.yml'
  # - 'code/**'
  # - 'entry.py'
  pull_request:
    branches:
    - main
    # paths:
# - '.github/workflows/python-checks.yml'
# - 'code/**'
# - 'entry.py'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Lint entry.py
      run: |
        pylint entry.py

    - name: Format entry.py
      run: |
        black entry.py

    - name: Run unit tests
      run: |
        pytest tests/test_entry.py

    - name: Measure code coverage
      run: |
        coverage run -m pytest tests/test_entry.py
        coverage report
        coverage xml

    - name: Report code coverage
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
